name: Deploy Docs
on:
  push:
    branches:
      - '*.x'
      - main
    tags:
      - '**'

  repository_dispatch:
    types: request-build-reference # legacy
  #schedule:
  #- cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:

permissions:
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dispatch-docs-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: docs-build
          fetch-depth: 1
          show-progress: false

      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD) -f build-refname=${{ github.ref_name }}

      - name: Dispatch (full build)
        if: github.ref_type == 'tag'
        run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD)
