name: Verify Staged Artifacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 5.0.0-M1, 5.1.0-RC1, 5.2.0 etc.'
        required: true
        type: string

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

jobs:
  verify-staged-with-samples:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Samples Repo
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-integration-samples
          ref: ${{ github.ref_name }}
          show-progress: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - uses: jfrog/setup-jfrog-cli@v3

      - name: Configure JFrog Cli
        run: jf gradlec --repo-resolve libs-staging-local

      - name: Verify Spring Integration Samples against staged release
        run: |
          sed -i "1,/springIntegrationVersion.*/s/springIntegrationVersion.*/springIntegrationVersion='${{ inputs.releaseVersion }}'/" build.gradle
          jf gradle check
